# Generated by Django 5.2.1 on 2025-05-18 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('learning', 'Learning'), ('learned', 'Learned')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Vocabulary',
                'verbose_name_plural': 'User Vocabularies',
                'ordering': ['word'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
