# Generated by Django 5.2.1 on 2025-05-18 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ru', 'Russian')], default='en', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'word', 'language')},
        ),
    ]
