# Generated by Django 5.2.1 on 2025-05-18 06:44

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_entries(apps, schema_editor):
    # Get the UserVocabulary model from the migration state
    UserVocabulary = apps.get_model('core', 'UserVocabulary')
    
    # Find duplicate entries based on user and word
    duplicates = (
        UserVocabulary.objects.values('user', 'word')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    # For each set of duplicates, keep only one entry
    for duplicate in duplicates:
        user_id = duplicate['user']
        word = duplicate['word']
        
        # Get all entries for this user and word
        entries = UserVocabulary.objects.filter(user_id=user_id, word=word).order_by('id')
        
        # Keep the first one, delete the rest
        first_entry = entries.first()
        entries.exclude(id=first_entry.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_entries),
    ] 