# Generated by Django 5.2.1 on 2025-05-18 06:45

from django.conf import settings
from django.db import migrations, models


def add_default_translations(apps, schema_editor):
    # Get the UserVocabulary model from the migration state
    UserVocabulary = apps.get_model('core', 'UserVocabulary')
    # Set a default translation for all existing records
    UserVocabulary.objects.all().update(translation='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_handle_duplicates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='translation',
            field=models.CharField(blank=True, help_text="Translation of the word in the user's native language", max_length=200, null=True),
        ),
        migrations.RunPython(add_default_translations),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'word')},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='uservocabulary',
            name='language',
        ),
    ] 