name: LexiParkRecorder
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM:
    PRODUCT_BUNDLE_IDENTIFIER: com.lexipark.recorder
targets:
  LexiParkRecorderApp:
    type: application
    platform: iOS
    sources:
      - LexiParkRecorderApp
      - Shared
    info:
      path: LexiParkRecorderApp/Info.plist
    entitlements:
      path: LexiParkRecorderApp/LexiParkRecorderApp.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lexipark.recorder
        CODE_SIGN_ENTITLEMENTS: LexiParkRecorderApp/LexiParkRecorderApp.entitlements
    dependencies: []
  RecorderExtension:
    type: app-extension
    platform: iOS
    sources:
      - RecorderExtension
      - Shared
    info:
      path: RecorderExtension/Info.plist
    entitlements:
      path: RecorderExtension/RecorderExtension.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lexipark.recorder.RecorderExtension
        CODE_SIGN_ENTITLEMENTS: RecorderExtension/RecorderExtension.entitlements
    scheme:
      testTargets: []
    dependencies:
      - target: LexiParkRecorderApp
schemes:
  LexiParkRecorder:
    build:
      targets:
        LexiParkRecorderApp: all
        RecorderExtension: all

