# Generated by Django 5.2.1 on 2025-05-31 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('learning', 'Learning'), ('learned', 'Learned')], default='unknown', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(default='ko', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularySetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vocabulary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyset')),
                ('vocabulary_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.uservocabulary')),
            ],
        ),
        migrations.AddIndex(
            model_name='uservocabulary',
            index=models.Index(fields=['user', 'status'], name='vocabulary__user_id_fe4a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='uservocabulary',
            index=models.Index(fields=['user', 'word'], name='vocabulary__user_id_392460_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'word', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='vocabularyset',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vocabularysetmembership',
            unique_together={('vocabulary_word', 'vocabulary_set')},
        ),
    ]
