# Generated by Django 5.2.1 on 2025-05-31 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='lemma',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabulary',
            unique_together={('user', 'lemma', 'language')},
        ),
        migrations.AddIndex(
            model_name='uservocabulary',
            index=models.Index(fields=['user', 'lemma'], name='vocabulary__user_id_5f1e52_idx'),
        ),
    ]
