# Generated by Django 5.2.1 on 2025-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_uservocabulary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabulary',
            name='vocabulary_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
